### ISSUE TITLE
Issues with 7in5_V2 screen since Waveshare Update 

### ISSUE THREAD

**Issue by TomWhitwell** [TomWhitwell/SlowMovie#143] opened 2023-01-11 21:27 UTC
Notes on the issue highlighted and worked around in #134 

Between [June 2021](https://github.com/waveshare/e-Paper/blob/b36cfab0ea336673982640ea21969e5a54714448/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd7in5b_V2.py) and [October 2022](https://github.com/waveshare/e-Paper/blob/7310e97ec1092a4e4fd5fb175978ba8135665ca6/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd7in5_V2.py)
there were two significant updates to epd7in5_V2.py in the Waveshare repo. 

1. The system for writing data over SPI was changed - `send_data2` uses  `spi_writebyte2` rather than `spi_writebyte`
This was discussed here back in #18 

2. `getBuffer` is significantly changed - I don't understand the changes there 

The impact on SlowMovie is that the screen is very streaky (see images in #134 ) if SlowMovie is installed or updated. 

The workaround is [explained here](https://github.com/TomWhitwell/SlowMovie/issues/134#issuecomment-1378829832) -  by @robweber 

I don't know if this impacts any other screens - there were a couple of [specific bugfixes](https://github.com/waveshare/e-Paper/commit/7310e97ec1092a4e4fd5fb175978ba8135665ca6) on epd7in5_V2.py 

I don't know which change (or something different) is causing the streaking.

**Comment by missionfloyd** [comment] 2023-01-12 00:47
This is caused by https://github.com/waveshare/e-Paper/commit/99f6a13540da0d4ad5a1291343068e0220f8b219

**Comment by robweber** [comment] 2023-01-13 16:59
What is a proper "fix" on the part of either SlowMovie or omni-epd for this? It seems to only affect a handful of displays (the 7.5 for sure). We could tag a specific Waveshare version but that might affect potential fixes for other issues across other devices in that same repo. Is this more of an FYI and we put some disclaimers up for people in various places in the README or install scripts?

**Comment by TomWhitwell** [comment] 2023-01-13 18:26
I don't know, I'm not sure of the best approach. 

It feels sad to me because all the work you've done to get a simple beginner-friendly one-line install now fails for the 'original' screen in the article and the default. 

Do you think that update of the 7.5 inch monochrome screen driver is just a mistake on their end - will it break anything trying to render complex images on the screen? I don't really understand the system well enough. Should I report it as a bug? Should they have implemented a new fast method that doesn't break the existing method? 

Options might be: 
* Change default and documentation to recommend another screen in a similar size that works properly
* Just document the one-line installation fix 
* Point to a specific waveshare version 
* Ask Waveshare to fix it

**Comment by robweber** [comment] 2023-02-10 21:19
Been thinking about this for a while - how does this sound for a tentative fix? 

1. Definitely file a bug with Waveshare - this may or may not go anywhere but fix at the source would be best
2. Add a disclaimer to both the README and install script regarding the issue with the 7.5in devices
3. Add a menu option in the install script to rollback the waveshare driver to the known working version

Thoughts?

**Comment by TomWhitwell** [comment] 2023-02-19 21:02
Hi Rob, hesitating on this because my OG VSMP isn't working - just did a completely fresh install of Raspberry OS, checked the mode switches on the hat, ran your fix above and I'm getting super noisy & streaky images, similarly with the waveshare test script - it's like it loads the image correctly, then as it refreshes, a lot of black pixels turn white. 

I think your suggestion sounds ideal, but not currently working for me unfortunately. 

![IMG_0971](https://user-images.githubusercontent.com/1890544/219974924-3dc2ad22-e71f-402e-9561-b00468b5d0d4.JPG)

**Comment by robweber** [comment] 2023-02-23 21:54
That's really bizarre given that the old version from above has fixed it before. I'm hesitant to mess up my own setup but I'll flash a new SD and do a clean install as well to see if I get the same result.

**Comment by TomWhitwell** [comment] 2023-02-24 06:17
I know - it feels more like a hardware problem - I reverted right back to my original code and it behaved the same. I think had it set in the wrong switch position for a while, wonder if that did some damage. 
BUT still, it's clearly receiving data and refreshing. So odd.

**Comment by robweber** [comment] 2023-02-24 21:33
I did a clean install of the most current branch of the waveshare python libraries. Noticed streaking on every image I tried to load. I uninstalled this and did an install using commit `b36cfab0ea336673982640ea21969e5a54714448` from above. Streaking stopped and things went back to normal. 

Your issue may very well be hardware related :(

**Comment by robweber** [comment] 2023-03-14 16:09
I've started a PR to add a disclaimer to the README and allow for the option to rollback the driver via the install script. Hopefully this should catch most use cases.

**Comment by robweber** [comment] 2023-05-12 15:25
Going to close this out since @missionfloyd has fixed this in the Waveshare lib.

**Closed by robweber** 2023-05-12 15:25 UTC
Labels: bug
